### ISSUE TITLE
Mailhog

### ISSUE THREAD

**Issue by digitall-it** [brettt89/silverstripe-web#10]
[Mailhog](https://github.com/mailhog/MailHog) should be installed, to test emails.

**Comment by brettt89** [comment]
Hi @digitall-it ,

Thank you for your feedback. I have kept this package fairly bare bones so that it cab be used for multiple applications.

As such I have not included sendmail or any mail service by default so that it is up to the user to define their use.

If you are wanting to use Mailhog, my suggestion would be to run a mailhog docker container separate from the brettt89/silverstripe-web container using docker-compose (E.g. the same way you connect a database) and then extend the functionality of brettt89/silverstripe-web by creating a Dockerfile with your customisations.

https://docs.docker.com/engine/reference/builder/#from
https://blog.philipphauer.de/test-mail-server-php-docker-container/


(This Dockerfile will add mailhog to the brettt89/silverstripe-web image)
E.g. Dockerfile
FROM brettt89/silverstripe-web:platform

ENV MAILHOG_VERSION v1.0.0

RUN curl -fsSL "https://github.com/mailhog/MailHog/releases/download/${MAILHOG_VERSION}/MailHog_linux_amd64" -o /usr/local/bin/mailhog && chmod +x /usr/local/bin/mailhog

RUN echo "sendmail_path=\"/usr/local/bin/mailhog sendmail --smtp-addr='<IP / HOSTNAME OF MAILHOG CONTAINER>:1025' docker@docker.dev\"" > /usr/local/etc/php/conf.d/mailhog.ini
