### ISSUE TITLE
Some error logs going missing

### ISSUE THREAD

**Issue by DigNZ** [brettt89/silverstripe-web#28]
Sometimes errors will come through xdebug and other times through SilverStripe (4), but a good number of errors will return 500 with nothing logged. I'm not sure if this is a configuration within the docker that can be resolved.

**Comment by brettt89** [comment]
Latest `master` version contains docker changes so that Error logs from Apache will also be piped to `docker logs`. This should help in identifying the errors being thrown by 500's.

I'm not sure if this issue you are facing is due to Xdebug configuraitons (e.g. error getting lost in transit). Or potentially Apache config / SilverStripe config in which PHP errors are not being shown.

Do you have your `SS_ENVIRONMENT_TYPE` set to `dev` instead of `prod`?

**Comment by brettt89** [comment]
Hi @DigNZ ,

We have just released a new version of these images which contain the changes mentioned above. PHP Errors, Warnings etc should now all be sent to the `docker logs` output along with access logs.
