### ISSUE TITLE
Install Composer to enable installation of projects

### ISSUE THREAD

**Issue by mleutenegger** [brettt89/silverstripe-web#46]
As Silverstripe is very composer-oriented, I think it would make sense to include a Version of composer directly in the image.

This would not only simplify Installation of modules, but also allow composer to check system requirements during install, leading to a more worry-free installation proccess (instead of using `--ignore-platform-reqs`).

I have opened this issue to discuss the usefulness of such a feature and would be happy to supply the code for it via PR.

**Comment by brettt89** [comment]
I have tried to keep these images as "light" as possible as per Docker design recommendations. This allows these images to be used in multiple situations (e.g. Development, Testing, Prodution, QA, etc) without making tpo many assumptions.

As Composer already has a docker image and guides on how to use, I would recommend looking at your workflow to see how you could implement the Composer image into your deployment flow instead of installing Composer directly onto the image.

However if you would like to add Composer, you can also do so locally by creating a `Dockerfile` and extending this image.

```
FROM brettt89/silverstripe-web
RUN #Install Composer
```

Personally I prefer to use Composer as an independent container to my web containers so that I am not having to load this overhead into my auto-scaling web boxes (E.g. Once composer has run for install, its not needed anymore).

I'm happy to discuss this and look at compromising if there is want/need for it, or if wanted, I could put together some more details guides on how to implement Composer into a docker workflow?

**Comment by mleutenegger** [comment]
Thanks for the arguments for leaving composer out of the image. 

as an enthusiastic and (at least somewhat) experienced Docker user I can understand and agree with the idea of keeping the image as light as possible. We have centered our entire dev process around Docker. Personally, I would also not want to include a composer installation in an Image for production use by default, as this would bloat the image. There, using a `COPY ... --from=<name>` to copy the working dir while using another image to build/install makes for a much lighter image.

In the case of testing however, things look a bit different from my perspective. We are using this image to test our modules and projects in github workflows (i.e. [syntro/silverstripe-klaro](https://github.com/syntro-opensource/silverstripe-klaro)). During these workflows, composer is crucial for installing dependencies and we have to include it by calling an install script in the job:

https://github.com/syntro-opensource/silverstripe-klaro/blob/4f9c087bab2f478dfca612ba14d0e9ff0a5aa352/.github/workflows/tests.yml#L38-L43

While the above example works, I think that this introduces a point of failure which has nothing to do with the module or project to be tested (if the composer install fails for example). 

Additionally, in our devenv tool ([ssdev](https://github.com/syntro-opensource/ssdev), which is basically a wrapper around docker-compose) we would like to be able to call composer require, install, update or remove inside the actual container, without having to append the `--ignore-platform-reqs` argument in the `composer:latest` container. Using this workaround introduces an uncertainty, as we would not know wether any package requires a specific php extension.

Both of the mentioned issues can be worked around, however I feel like there is an argument for having an image which has composer baked in. While it would be possible to maintain an image myself, this would basically just be a proxy adding composer to this image.

What I could imagine being useful would be to add a version of this image which contains composer, alongside the ones without it, like `brettt89/silverstripe-web:7.4-apache-composer`. What would you think about this Idea?

**Comment by brettt89** [comment]
The trouble with adding another tagged component such as `composer` is that the question becomes "Which existing releases should also be included".

You then end up with a compounded growing list of tagged versions for minor differences (such as whether or not `composer` is installed).

E.g. (Just PHP 7.4)
7.4-apache
7.4-cli
7.4-fpm
7.4-apache-composer
7.4-cli-composer
7.3-fpm-composer

This model doesn't scale very well as if this approach is used once, it is often requested for other components which people believe should be included.

## Alternative solution

Composer offers the ability to "assume platform configuration" within the `composer.json` file of your project. https://getcomposer.org/doc/06-config.md#platform

E.g. This tells composer to emulate these PHP versions and extensions on the project so that you are not required to use `--ignore-platform-reqs`
```
{
 "config": {
   "platform": {
     "php": "MAJOR.MINOR.PATCH",
     "ext-something": "1"
   }
 }
}
```

If you have this in your project, then you can use `composer:latest` to install your project requirements as it will emulate these config options instead of throwing an error that the Host doesn't match requirements.

You are not using `composer` to validate your hardware / infrastructure (otherwise you would be doing this on Prod directly). So essentially you are just using Composer to install the required modules for the PHP version defined (incase different tagged versions are used for different PHP versions etc).

**Comment by mleutenegger** [comment]
Thanks for the proposed solution, we already use that exact approach in client projects. As stated before, I opened this issue to discuss the feasability of adding composer and there is no need to fix anything as nothing is broken 😉 

I can fully agree with your argument for not adding more tags, as there are already many of them. I also agree with the latter argument, as this might open the door for more requests. 

I think, one could expand on the documentation a little bit to make clear that this should be a minimal base image and guide a possible user more easily through the process of building his own image, for example with specific docs per topic. I think I will try and throw up some docs about the topic when I have the time for it and open a PR. I consider this discussion resolved and will close the issue, thanks for your time and patience!
