### ISSUE TITLE
Useful utilities

### ISSUE THREAD

**Issue by digitall-it** [brettt89/silverstripe-web#9]
Some utilities should be installed by default:

- rsync
- wget
- telnet

**Comment by brettt89** [comment]
Hi @digitall-it ,

Thank you for your feedback. I have kept this package fairly bare bones so that it cab be used for multiple applications.

Is there any reason as to why you find these utilities should be installed? E.g. what use case have you used them for so far?

Also, something more suited for you may be to use a Dockerfile for your project and using "brettt89/silverstripe-web" as a base.

E.g. Dockerfile
FROM brettt89/silverstripe-web:platform
RUN apt-get update -y && apt-get install -y \
    rsync \
    wget \
    telnet


This would allow you to leverage the brettt89/silverstripe-web docker image while still applying your own customisations.
